### ISSUE TITLE
RP2

### ISSUE THREAD

**Issue by eprbell** [haunticaachris/crypto#3]
Hello, 
I designed and implemented RP2, an open-source, privacy-focused, free, non-commercial crypto tax calculator (https://github.com/eprbell/rp2). Would you consider adding it to your list? 

Another suggestion is to create a tax-specific category, containing only tax tools.

Thanks!

**Comment by haunticaachris** [comment]
Good idea adding a tax category I will go ahead and add RP2 to it as well as I have already seen it and like it a lot.

Thank you

**Comment by eprbell** [comment]
Thanks!
